import http from "node:http";

const PORT = Number(process.env.PORT || 3000);
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;
async function sb(path){if(!SUPABASE_URL||!SUPABASE_KEY)return [];const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY}});return r.ok?await r.json():[];}
async function sbWrite(path,method,body){if(!SUPABASE_URL||!SUPABASE_KEY)return false;const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{method,headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY,"content-type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(body)});return r.ok;}

const page = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>FERVAL CONTROL</title><style>*{box-sizing:border-box}body{margin:0;background:#07111f;color:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.app{max-width:760px;margin:auto;height:100dvh;display:flex;flex-direction:column}.head{padding:18px;border-bottom:1px solid #263449}.head b{font-size:19px}.head span{display:block;color:#94a3b8;font-size:12px;margin-top:4px}.chat{flex:1;overflow:auto;padding:18px;display:flex;flex-direction:column;gap:12px}.m{max-width:86%;padding:12px 14px;border-radius:16px;line-height:1.35;white-space:pre-wrap}.u{align-self:flex-end;background:#2563eb}.a{align-self:flex-start;background:#1e293b}.bar{display:flex;gap:8px;padding:12px;border-top:1px solid #263449}.bar input{flex:1;background:#111c2e;color:white;border:1px solid #334155;border-radius:14px;padding:14px;font-size:16px}.bar button{border:0;border-radius:14px;padding:0 18px;font-weight:700}.status{color:#64748b;font-size:11px;padding:0 18px 8px}</style></head><body><div class="app"><div class="head"><b>FERVAL CONTROL</b><span>Dirección · YAYO</span></div><div id="chat" class="chat"><div class="m a">Estoy aquí. ¿Qué necesitas?</div></div><div id="s" class="status"></div><form id="f" class="bar"><input id="i" autocomplete="off" placeholder="Escribe a Yayo…"><button>Enviar</button></form></div><script>const f=document.getElementById('f'),i=document.getElementById('i'),c=document.getElementById('chat'),s=document.getElementById('s');let history=[];const sid=localStorage.ferval_sid||(localStorage.ferval_sid=crypto.randomUUID());const add=(t,k)=>{const d=document.createElement('div');d.className='m '+k;d.textContent=t;c.appendChild(d);c.scrollTop=c.scrollHeight};fetch('/api/history?sid='+encodeURIComponent(sid)).then(r=>r.json()).then(j=>{if(Array.isArray(j.history)){history=j.history;for(const x of history)add(x.content,x.role==='assistant'?'a':'u')}}).catch(()=>{});f.onsubmit=async e=>{e.preventDefault();const m=i.value.trim();if(!m)return;i.value='';add(m,'u');history.push({role:'user',content:m});s.textContent='Yayo está pensando…';try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:m,history:history.slice(0,-1),sid})});const j=await r.json();const answer=j.reply||j.error||'No he podido responder.';add(answer,'a');history.push({role:'assistant',content:answer})}catch(e){add('No he podido conectar.','a')}finally{s.textContent='';i.focus()}};</script></body></html>`;

const json=(res,status,obj)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(obj));};

http.createServer(async (req,res)=>{
  if(req.method==="GET" && req.url==="/"){res.writeHead(200,{"content-type":"text/html; charset=utf-8"});return res.end(page);}
  if(req.method==="GET" && req.url==="/health") return json(res,200,{ok:true});
  if(req.method==="GET" && req.url.startsWith("/api/history")){const u=new URL(req.url,"http://localhost");const sid=u.searchParams.get("sid")||"";if(!sid)return json(res,200,{history:[]});const rows=await sb("yayo_session_messages?session_key=eq."+encodeURIComponent(sid)+"&select=role,body&order=id.asc&limit=100");return json(res,200,{history:rows.map(x=>({role:x.role,content:x.body}))});}
  if(req.method==="POST" && req.url==="/api/chat"){
    let body=""; for await (const chunk of req) body+=chunk;
    let message="",history=[],sid="";try{const p=JSON.parse(body);message=p.message||"";history=Array.isArray(p.history)?p.history.slice(-20):[];sid=String(p.sid||"")}catch{return json(res,400,{error:"Mensaje inválido."})}
    if(sid){await sbWrite("yayo_sessions?on_conflict=session_key","POST",{session_key:sid,display_name:"Rubén",access_level:"N1"});const rows=await sb("yayo_session_messages?session_key=eq."+encodeURIComponent(sid)+"&select=role,body&order=id.desc&limit=30");if(rows.length)history=rows.reverse().map(x=>({role:x.role,content:x.body}));await sbWrite("yayo_session_messages","POST",{session_key:sid,role:"user",body:message});}
    if(!OPENAI_API_KEY) return json(res,503,{error:"Falta configurar OPENAI_API_KEY."});
    try{
      const [mem,obras]=await Promise.all([sb("yayo_memory?select=scope,memory_key,content&limit=100"),sb("obras?select=codigo,nombre,estado,notas&order=codigo")]);const input=[...history.map(x=>({role:x.role==="assistant"?"assistant":"user",content:String(x.content||"")})),{role:"user",content:message}];const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"authorization":"Bearer "+OPENAI_API_KEY,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6",instructions:"Eres Yayo, IA operativa y asistente de Dirección dentro de FERVAL CONTROL. Tu interlocutor principal es Rubén, Dirección de Grupo Ferval. Rubén y Yayo trabajan como Dirección asistida: Rubén aporta criterio y decisión final; Yayo aporta memoria, análisis, contraste y seguimiento. FERVAL CONTROL es la puerta y memoria operativa. Antes de decir que no sabes algo, consulta CONTEXTO FERVAL. No inventes. Distingue registrado, informado, calculado, previsto, pendiente y no registrado. Si Rubén pregunta quién es, reconoce su función de Dirección. Si pregunta por otro usuario, entiende que cada usuario debe tener su propia sesión y conversación, nunca compartir el chat de Rubén. Si pide una obra por código, usa los datos disponibles. Habla directo y natural, evitando respuestas genéricas de chatbot. CONTEXTO FERVAL: "+JSON.stringify({memoria:mem,obras}),input})});
      const data=await r.json();
      if(!r.ok) return json(res,r.status,{error:data?.error?.message||"Error de OpenAI."});
      const reply=data.output_text || (data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text).join("\n") || "Sin respuesta.";
      if(sid)await sbWrite("yayo_session_messages","POST",{session_key:sid,role:"assistant",body:reply});return json(res,200,{reply});
    }catch(e){return json(res,500,{error:"Error conectando con OpenAI."})}
  }
  json(res,404,{error:"Not found"});
}).listen(PORT,"0.0.0.0",()=>console.log("FERVAL CONTROL listening on",PORT));