-- IAYO PRIVATE 0.1 — apply ONLY to the future dedicated PRIVATE project.
create table private_profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text not null, owner boolean not null default false, created_at timestamptz not null default now());
create table private_sessions (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, session_key uuid not null unique default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table private_messages (id bigint generated by default as identity primary key, session_id bigint not null references private_sessions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check(role in ('user','assistant','system')), body text not null, created_at timestamptz not null default now());
create table private_memory (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, memory_key text not null, content jsonb not null, source text not null, status text not null default 'validated', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,memory_key));
create table private_memory_candidates (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, content jsonb not null, source text not null, status text not null default 'candidate', created_at timestamptz not null default now());
create table private_state (user_id uuid primary key references auth.users(id) on delete cascade, state jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table private_reflections (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, reflection jsonb not null, created_at timestamptz not null default now());
create table private_outcomes (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, subject text not null, outcome jsonb not null, created_at timestamptz not null default now());
create table private_initiatives (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, message text not null, reason text, priority text not null default 'normal', status text not null default 'pending', created_at timestamptz not null default now());
create table private_push_subscriptions (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, endpoint text not null unique, subscription jsonb not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table private_audit_log (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null, event text not null, detail jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

alter table private_profiles enable row level security;
alter table private_sessions enable row level security;
alter table private_messages enable row level security;
alter table private_memory enable row level security;
alter table private_memory_candidates enable row level security;
alter table private_state enable row level security;
alter table private_reflections enable row level security;
alter table private_outcomes enable row level security;
alter table private_initiatives enable row level security;
alter table private_push_subscriptions enable row level security;
alter table private_audit_log enable row level security;

create policy own_profile on private_profiles for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_sessions on private_sessions for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_messages on private_messages for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_memory on private_memory for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_candidates on private_memory_candidates for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_state on private_state for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_reflections on private_reflections for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_outcomes on private_outcomes for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_initiatives on private_initiatives for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_push on private_push_subscriptions for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy own_audit_read on private_audit_log for select to authenticated using ((select auth.uid())=user_id);
